# Generated by Django 3.0.2 on 2020-02-12 17:51

from django.db import migrations, models
import django.db.models.deletion
import richieste.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vetture_service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Richiesta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imei', models.CharField(max_length=100)),
                ('tipologia', models.CharField(choices=[('Incidente stradale', 'Incidente stradale'), ('Incidente', 'Incidente'), ('Incendio', 'Incendio'), ('Dissesti statici', 'Dissesti statici'), ('Furto', 'Furto'), ('Violenza domestica', 'Violenza domestica'), ('Malore improvviso', 'Malore improvviso'), ('Altro', 'Altro'), ('Supporto', 'Supporto')], max_length=100, null=True)),
                ('forza_ordine', models.CharField(choices=[('Polizia', 'Polizia'), ('Carabinieri', 'Carabinieri'), ('Paramedici', 'Paramedici'), ('Pompieri', 'Pompieri')], max_length=100, null=True)),
                ('is_supporto', models.CharField(default=None, max_length=100, null=True)),
                ('stato', models.CharField(choices=[('Creata', 'Creata'), ('Presa in carico', 'Presa in carico'), ('Risolta', 'Risolta')], max_length=100, null=True)),
                ('informazioni', models.CharField(max_length=300, null=True)),
                ('data', models.CharField(max_length=100, null=True)),
                ('linea_verde_richiesta', models.BooleanField(default=False)),
                ('long', models.CharField(max_length=100, null=True)),
                ('lat', models.CharField(max_length=100, null=True)),
                ('playerId', models.CharField(default='', max_length=36)),
                ('tempoDiArrivo', models.IntegerField(default=None, null=True)),
                ('vettura', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='vetture_service.Vettura')),
            ],
        ),
        migrations.CreateModel(
            name='Allegato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(max_length=500, null=True, upload_to=richieste.models.content_file_name)),
                ('richiesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='richieste.Richiesta')),
            ],
        ),
    ]
