# Generated by Django 3.0.2 on 2020-01-27 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Richiesta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imei', models.CharField(max_length=100, unique=True)),
                ('tipologia', models.CharField(choices=[('Incidente', 'Incidente'), ('Incendio', 'Incendio'), ('Dissesti statici', 'Dissesti statici'), ('Altro', 'Altro')], max_length=100, null=True)),
                ('stato', models.CharField(choices=[('Creata', 'Creata'), ('Presa in carico', 'Presa in carico'), ('Risolta', 'Risolta')], max_length=100, null=True)),
                ('informazioni', models.CharField(max_length=300, null=True)),
                ('data', models.DateField(null=True)),
                ('linea_verde_richiesta', models.BooleanField(default=False)),
                ('long', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Allegato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(null=True, upload_to='')),
                ('richiesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='richieste.Richiesta')),
            ],
        ),
    ]
