# Generated by Django 3.0.2 on 2020-01-27 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('richieste', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='richiesta',
            name='imei',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='richiesta',
            name='lat',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='richiesta',
            name='long',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
