# Generated by Django 3.0.2 on 2020-01-28 17:08

from django.db import migrations, models
import richieste.models


class Migration(migrations.Migration):

    dependencies = [
        ('richieste', '0002_auto_20200127_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allegato',
            name='file',
            field=models.FileField(null=True, upload_to=richieste.models.content_file_name),
        ),
        migrations.AlterField(
            model_name='richiesta',
            name='data',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
