# Generated by Django 3.0.2 on 2020-01-28 17:41

from django.db import migrations, models
import richieste.models


class Migration(migrations.Migration):

    dependencies = [
        ('richieste', '0003_auto_20200128_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allegato',
            name='file',
            field=models.FileField(max_length=500, null=True, upload_to=richieste.models.content_file_name),
        ),
    ]
