# Generated by Django 3.0.2 on 2020-01-31 00:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vetture_service', '0008_auto_20200130_1342'),
        ('richieste', '0004_auto_20200128_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='richiesta',
            name='vettura',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='vetture_service.Vettura'),
        ),
    ]
