# Generated by Django 3.0.2 on 2020-01-31 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('richieste', '0005_richiesta_vettura'),
    ]

    operations = [
        migrations.AddField(
            model_name='richiesta',
            name='playerId',
            field=models.CharField(default='', max_length=36),
        ),
    ]
