# Generated by Django 3.0.2 on 2020-02-04 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('richieste', '0006_richiesta_playerid'),
    ]

    operations = [
        migrations.AddField(
            model_name='richiesta',
            name='is_supporto',
            field=models.CharField(choices=[('True', 'True'), ('False', 'False')], default='False', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='richiesta',
            name='tempoDiArrivo',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='richiesta',
            name='tipologia',
            field=models.CharField(choices=[('Incidente', 'Incidente'), ('Incendio', 'Incendio'), ('Dissesti statici', 'Dissesti statici'), ('Furto', 'Furto'), ('Violenza domestica', 'Violenza domestica'), ('Malore improvviso', 'Malore improvviso'), ('Altro', 'Altro')], max_length=100, null=True),
        ),
    ]
