# Generated by Django 3.0.2 on 2020-01-24 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vettura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificativo', models.CharField(max_length=100, unique=True)),
                ('tipologia', models.CharField(choices=[('AV', 'Autovettura'), ('MC', 'Motociclo'), ('CR', 'Corazzato'), ('EC', 'Elicottero'), ('AB', 'Ambulanza')], max_length=100)),
                ('stato', models.CharField(choices=[('O', 'Operativa'), ('NO', 'Non Operativa')], max_length=100)),
                ('imei', models.CharField(max_length=15, unique=True)),
                ('playerId', models.CharField(max_length=36, unique=True)),
            ],
        ),
    ]
