# Generated by Django 3.0.2 on 2020-02-06 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vettura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificativo', models.CharField(max_length=100, unique=True)),
                ('tipologia', models.CharField(choices=[('Autovettura', 'Autovettura'), ('Motociclo', 'Motociclo'), ('Autocarro', 'Autocarro'), ('Elicottero', 'Elicottero'), ('Ambulanza', 'Ambulanza')], max_length=100)),
                ('forza_ordine', models.CharField(choices=[('Polizia', 'Polizia'), ('Carabinieri', 'Carabinieri'), ('Paramedici', 'Paramedici'), ('Pompieri', 'Pompieri')], max_length=100, null=True)),
                ('stato', models.CharField(choices=[('Operativa', 'Operativa'), ('Non Operativa', 'Non Operativa')], max_length=100)),
                ('imei', models.CharField(max_length=15)),
                ('playerId', models.CharField(max_length=36)),
                ('disponibile', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Posizione',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long', models.CharField(max_length=20, null=True)),
                ('lat', models.CharField(max_length=20, null=True)),
                ('ultimo_aggiornamento', models.DateTimeField(null=True)),
                ('vettura', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vetture_service.Vettura')),
            ],
        ),
    ]
