# Generated by Django 3.0.2 on 2020-01-25 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vetture_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vettura',
            name='imei',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='vettura',
            name='playerId',
            field=models.CharField(max_length=36),
        ),
        migrations.AlterField(
            model_name='vettura',
            name='stato',
            field=models.CharField(choices=[('Operativa', 'Operativa'), ('Non Operativa', 'Non Operativa')], max_length=100),
        ),
        migrations.AlterField(
            model_name='vettura',
            name='tipologia',
            field=models.CharField(choices=[('Autovettura', 'Autovettura'), ('Motociclo', 'Motociclo'), ('Corazzato', 'Corazzato'), ('Elicottero', 'Elicottero'), ('Ambulanza', 'Ambulanza')], max_length=100),
        ),
    ]
