# Generated by Django 3.0.2 on 2020-01-26 00:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vetture_service', '0002_auto_20200125_1803'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posizione',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long', models.DecimalField(decimal_places=6, max_digits=9)),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('ultimo_aggiornamento', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='vettura',
            name='posizione',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vetture_service.Posizione'),
        ),
    ]
