# Generated by Django 3.0.2 on 2020-01-26 00:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vetture_service', '0003_auto_20200126_0132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vettura',
            name='posizione',
        ),
        migrations.AddField(
            model_name='posizione',
            name='vettura',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vetture_service.Vettura'),
        ),
    ]
