# Generated by Django 3.0.2 on 2020-01-26 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vetture_service', '0004_auto_20200126_0138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posizione',
            name='lat',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='posizione',
            name='long',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
    ]
