# Generated by Django 3.0.2 on 2020-01-26 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vetture_service', '0005_auto_20200126_0144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posizione',
            name='ultimo_aggiornamento',
            field=models.DateTimeField(null=True),
        ),
    ]
