# Generated by Django 3.0.2 on 2020-01-27 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vetture_service', '0006_auto_20200126_0144'),
    ]

    operations = [
        migrations.AddField(
            model_name='vettura',
            name='disponibile',
            field=models.BooleanField(default=True),
        ),
    ]
