# Generated by Django 3.0.2 on 2020-01-30 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vetture_service', '0007_vettura_disponibile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posizione',
            name='lat',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='posizione',
            name='long',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
