# Generated by Django 3.0.2 on 2020-02-04 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vetture_service', '0009_vettura_forza_ordine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vettura',
            name='tipologia',
            field=models.CharField(choices=[('Autovettura', 'Autovettura'), ('Motociclo', 'Motociclo'), ('Autocarro', 'Autocarro'), ('Elicottero', 'Elicottero'), ('Ambulanza', 'Ambulanza')], max_length=100),
        ),
    ]
